// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/test.proto

package com.antiphon.protobuf;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2S_TEST_1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 type = 1;
    boolean hasType();
    int getType();
    
    // required string secretKey = 2;
    boolean hasSecretKey();
    String getSecretKey();
  }
  public static final class C2S_TEST_1 extends
      com.google.protobuf.GeneratedMessage
      implements C2S_TEST_1OrBuilder {
    // Use C2S_TEST_1.newBuilder() to construct.
    private C2S_TEST_1(Builder builder) {
      super(builder);
    }
    private C2S_TEST_1(boolean noInit) {}
    
    private static final C2S_TEST_1 defaultInstance;
    public static C2S_TEST_1 getDefaultInstance() {
      return defaultInstance;
    }
    
    public C2S_TEST_1 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.antiphon.protobuf.TestProto.internal_static_rxzq_C2S_TEST_1_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.antiphon.protobuf.TestProto.internal_static_rxzq_C2S_TEST_1_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // required string secretKey = 2;
    public static final int SECRETKEY_FIELD_NUMBER = 2;
    private java.lang.Object secretKey_;
    public boolean hasSecretKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSecretKey() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          secretKey_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSecretKeyBytes() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        secretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      type_ = 0;
      secretKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecretKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSecretKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSecretKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.antiphon.protobuf.TestProto.C2S_TEST_1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.antiphon.protobuf.TestProto.C2S_TEST_1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.antiphon.protobuf.TestProto.C2S_TEST_1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.antiphon.protobuf.TestProto.internal_static_rxzq_C2S_TEST_1_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.antiphon.protobuf.TestProto.internal_static_rxzq_C2S_TEST_1_fieldAccessorTable;
      }
      
      // Construct using com.antiphon.protobuf.TestProto.C2S_TEST_1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        secretKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.antiphon.protobuf.TestProto.C2S_TEST_1.getDescriptor();
      }
      
      public com.antiphon.protobuf.TestProto.C2S_TEST_1 getDefaultInstanceForType() {
        return com.antiphon.protobuf.TestProto.C2S_TEST_1.getDefaultInstance();
      }
      
      public com.antiphon.protobuf.TestProto.C2S_TEST_1 build() {
        com.antiphon.protobuf.TestProto.C2S_TEST_1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.antiphon.protobuf.TestProto.C2S_TEST_1 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.antiphon.protobuf.TestProto.C2S_TEST_1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.antiphon.protobuf.TestProto.C2S_TEST_1 buildPartial() {
        com.antiphon.protobuf.TestProto.C2S_TEST_1 result = new com.antiphon.protobuf.TestProto.C2S_TEST_1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.secretKey_ = secretKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.antiphon.protobuf.TestProto.C2S_TEST_1) {
          return mergeFrom((com.antiphon.protobuf.TestProto.C2S_TEST_1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.antiphon.protobuf.TestProto.C2S_TEST_1 other) {
        if (other == com.antiphon.protobuf.TestProto.C2S_TEST_1.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSecretKey()) {
          setSecretKey(other.getSecretKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSecretKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              secretKey_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required string secretKey = 2;
      private java.lang.Object secretKey_ = "";
      public boolean hasSecretKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSecretKey() {
        java.lang.Object ref = secretKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          secretKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSecretKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        secretKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecretKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        secretKey_ = getDefaultInstance().getSecretKey();
        onChanged();
        return this;
      }
      void setSecretKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        secretKey_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:rxzq.C2S_TEST_1)
    }
    
    static {
      defaultInstance = new C2S_TEST_1(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rxzq.C2S_TEST_1)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rxzq_C2S_TEST_1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rxzq_C2S_TEST_1_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProtoFile/test.proto\022\004rxzq\"-\n\nC2S_TEST" +
      "_1\022\014\n\004type\030\001 \002(\005\022\021\n\tsecretKey\030\002 \002(\tB\"\n\025c" +
      "om.antiphon.protobufB\tTestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rxzq_C2S_TEST_1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rxzq_C2S_TEST_1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rxzq_C2S_TEST_1_descriptor,
              new java.lang.String[] { "Type", "SecretKey", },
              com.antiphon.protobuf.TestProto.C2S_TEST_1.class,
              com.antiphon.protobuf.TestProto.C2S_TEST_1.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
