package avatar.protobuf;

import avatar.protobuf.Cmd;
import com.google.protobuf.InvalidProtocolBufferException;public class DeSerialize {@SuppressWarnings("unchecked")public static <T> T decode(int msg_type, byte[] msg) throws InvalidProtocolBufferException {if(msg == null) {return null;}switch(msg_type){case Cmd.C2S_LOGIN:return (T)Login.LoginC2S.parseFrom(msg);
case Cmd.C2S_Hall_CREATE_ROOM:return (T)Hall.CheckCreateRoomC2S.parseFrom(msg);
case Cmd.C2S_Hall_GET_CHECKIN_INFO:return (T)Hall.GetCheckInInfoC2S.parseFrom(msg);
case Cmd.C2S_Hall_CHECKIN:return (T)Hall.CheckInC2S.parseFrom(msg);
case Cmd.C2S_Hall_GET_USERINFO:return (T)Hall.GetUserInfoC2S.parseFrom(msg);
case Cmd.C2S_Hall_GET_CHECKIN_REWARD:return (T)Hall.GetCheckInRewardC2S.parseFrom(msg);
case Cmd.C2S_Hall_JOIN_IN_ROOM:return (T)Hall.JoinInRoomC2S.parseFrom(msg);
case Cmd.C2S_Hall_GET_BATTLE_HISTORY:return (T)Hall.GetGradeInfoC2S.parseFrom(msg);
case Cmd.C2S_Hall_GET_BATTLE_DETAIL:return (T)Hall.GetRoundInfoC2S.parseFrom(msg);
case Cmd.C2S_Hall_CHECK_APPLY_STATUS:return (T)Hall.CheckApplyStatusC2S.parseFrom(msg);
case Cmd.C2S_Hall_APPLY_COMPETITION:return (T)Hall.ApplyCompetitionC2S.parseFrom(msg);
case Cmd.C2S_Hall_JOIN_COMPETITION:return (T)Hall.JoinCompetitionC2S.parseFrom(msg);
case Cmd.C2S_Hall_Check_Invitation_Code:return (T)Hall.CheckInvitationCodeC2S.parseFrom(msg);
case Cmd.C2S_Hall_Match:return (T)Hall.ApplyMatchingC2S.parseFrom(msg);
case Cmd.C2S_Hall_Cancel_Match:return (T)Hall.CancelMatchingC2S.parseFrom(msg);
case Cmd.C2S_Hall_Get_Ranking_List:return (T)Hall.GetRankingListC2S.parseFrom(msg);
case Cmd.C2S_Hall_Get_UserInfo_By_Id:return (T)Hall.GetUserInfoByIdC2S.parseFrom(msg);
case Cmd.C2S_Hall_Get_Replay_Data:return (T)Hall.PlayVideoC2S.parseFrom(msg);
case Cmd.C2S_Hall_Reconnect:return (T)Hall.ReConnectC2S.parseFrom(msg);
case Cmd.C2S_HALL_BATTLEBEAT:return (T)Hall.HallBeatC2S.parseFrom(msg);
case Cmd.C2S_ENTER_ROOM:return (T)Battle.EnterRoomServerC2S.parseFrom(msg);
case Cmd.C2S_ROOM_JOIN_ROOM:return (T)Battle.JoinRoomC2S.parseFrom(msg);
case Cmd.C2S_ROOM_READY:return (T)Battle.ReadyC2S.parseFrom(msg);
case Cmd.C2S_ROOM_DISSOLVE:return (T)Battle.DissolveRoomC2S.parseFrom(msg);
case Cmd.C2S_ROOM_EXIT:return (T)Battle.ExitRoomC2S.parseFrom(msg);
case Cmd.C2S_ROOM_APPLY_DISSOLVE:return (T)Battle.ApplyDissolveRoomC2S.parseFrom(msg);
case Cmd.C2S_ROOM_CANCEL_APPLY_DISSOLVE:return (T)Battle.CancelDissolveRoomC2S.parseFrom(msg);
case Cmd.C2S_ROOM_Comfirm_Dissolve:return (T)Battle.DissloveRoomConfirmC2S.parseFrom(msg);
case Cmd.C2S_ROOM_PLAY_A_MAHJONG:return (T)Battle.PlayAMahjongC2S.parseFrom(msg);
case Cmd.C2S_ROOM_PASS:return (T)Battle.GuoC2S.parseFrom(msg);
case Cmd.C2S_ROOM_PENG:return (T)Battle.PengC2S.parseFrom(msg);
case Cmd.C2S_ROOM_CHI:return (T)Battle.ChiC2S.parseFrom(msg);
case Cmd.C2S_ROOM_COMMON_AN_GANG:return (T)Battle.CommonAnGangC2S.parseFrom(msg);
case Cmd.C2S_ROOM_BACK_AN_GANG:return (T)Battle.BackAnGangC2S.parseFrom(msg);
case Cmd.C2S_ROOM_ZHI_GANG:return (T)Battle.ZhiGangC2S.parseFrom(msg);
case Cmd.C2S_ROOM_COMMON_PENG_GANG:return (T)Battle.CommonPengGangC2S.parseFrom(msg);
case Cmd.C2S_ROOM_BACK_PENG_GANG:return (T)Battle.BackPengGangC2S.parseFrom(msg);
case Cmd.C2S_ROOM_ZI_MO_HU:return (T)Battle.ZiMoHuC2S.parseFrom(msg);
case Cmd.C2S_ROOM_QIANG_ZHI_GANG_HU:return (T)Battle.QiangZhiGangHuC2S.parseFrom(msg);
case Cmd.C2S_ROOM_QIANG_AN_GANG_HU:return (T)Battle.QiangAnGangHuC2S.parseFrom(msg);
case Cmd.C2S_ROOM_QIANG_PENG_GANG_HU:return (T)Battle.QiangPengGangHuC2S.parseFrom(msg);
case Cmd.C2S_ROOM_CHI_HU:return (T)Battle.ChiHuC2S.parseFrom(msg);
case Cmd.C2S_ROOM_BATTLEBEAT:return (T)Battle.BattleBeatC2S.parseFrom(msg);
case Cmd.C2S_ROOM_ONLINESETTING:return (T)Battle.OnlineSettingC2S.parseFrom(msg);
case Cmd.C2S_ROOM_TEXT_CHAT:return (T)Battle.SendChatC2S.parseFrom(msg);
case Cmd.C2S_ROOM_VOICE_CHAT:return (T)Battle.SendVoiceC2S.parseFrom(msg);
}System.out.println("[InnerDeSerialize]decodeInner,cmd failed. cmd = " + msg_type);
        return null;}}