// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/LoginMsg.proto

package avatar.protobuf;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginC2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string mac = 1;
    boolean hasMac();
    String getMac();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required string psw = 3;
    boolean hasPsw();
    String getPsw();
    
    // required string imageUrl = 4;
    boolean hasImageUrl();
    String getImageUrl();
    
    // required int32 sex = 5;
    boolean hasSex();
    int getSex();
  }
  public static final class LoginC2S extends
      com.google.protobuf.GeneratedMessage
      implements LoginC2SOrBuilder {
    // Use LoginC2S.newBuilder() to construct.
    private LoginC2S(Builder builder) {
      super(builder);
    }
    private LoginC2S(boolean noInit) {}
    
    private static final LoginC2S defaultInstance;
    public static LoginC2S getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginC2S getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Login.internal_static_Platform_Model_LoginC2S_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Login.internal_static_Platform_Model_LoginC2S_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string mac = 1;
    public static final int MAC_FIELD_NUMBER = 1;
    private java.lang.Object mac_;
    public boolean hasMac() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMac() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mac_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMacBytes() {
      java.lang.Object ref = mac_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mac_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string psw = 3;
    public static final int PSW_FIELD_NUMBER = 3;
    private java.lang.Object psw_;
    public boolean hasPsw() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPsw() {
      java.lang.Object ref = psw_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          psw_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPswBytes() {
      java.lang.Object ref = psw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        psw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string imageUrl = 4;
    public static final int IMAGEURL_FIELD_NUMBER = 4;
    private java.lang.Object imageUrl_;
    public boolean hasImageUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imageUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 sex = 5;
    public static final int SEX_FIELD_NUMBER = 5;
    private int sex_;
    public boolean hasSex() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getSex() {
      return sex_;
    }
    
    private void initFields() {
      mac_ = "";
      name_ = "";
      psw_ = "";
      imageUrl_ = "";
      sex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPsw()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImageUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMacBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPswBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImageUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sex_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMacBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPswBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImageUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Login.LoginC2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Login.LoginC2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Login.LoginC2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Login.LoginC2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Login.internal_static_Platform_Model_LoginC2S_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Login.internal_static_Platform_Model_LoginC2S_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Login.LoginC2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mac_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        psw_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        imageUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Login.LoginC2S.getDescriptor();
      }
      
      public avatar.protobuf.Login.LoginC2S getDefaultInstanceForType() {
        return avatar.protobuf.Login.LoginC2S.getDefaultInstance();
      }
      
      public avatar.protobuf.Login.LoginC2S build() {
        avatar.protobuf.Login.LoginC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Login.LoginC2S buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Login.LoginC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Login.LoginC2S buildPartial() {
        avatar.protobuf.Login.LoginC2S result = new avatar.protobuf.Login.LoginC2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mac_ = mac_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.psw_ = psw_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.imageUrl_ = imageUrl_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sex_ = sex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Login.LoginC2S) {
          return mergeFrom((avatar.protobuf.Login.LoginC2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Login.LoginC2S other) {
        if (other == avatar.protobuf.Login.LoginC2S.getDefaultInstance()) return this;
        if (other.hasMac()) {
          setMac(other.getMac());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPsw()) {
          setPsw(other.getPsw());
        }
        if (other.hasImageUrl()) {
          setImageUrl(other.getImageUrl());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMac()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasPsw()) {
          
          return false;
        }
        if (!hasImageUrl()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mac_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              psw_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              imageUrl_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sex_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string mac = 1;
      private java.lang.Object mac_ = "";
      public boolean hasMac() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMac() {
        java.lang.Object ref = mac_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mac_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMac(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mac_ = value;
        onChanged();
        return this;
      }
      public Builder clearMac() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mac_ = getDefaultInstance().getMac();
        onChanged();
        return this;
      }
      void setMac(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        mac_ = value;
        onChanged();
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required string psw = 3;
      private java.lang.Object psw_ = "";
      public boolean hasPsw() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPsw() {
        java.lang.Object ref = psw_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          psw_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPsw(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        psw_ = value;
        onChanged();
        return this;
      }
      public Builder clearPsw() {
        bitField0_ = (bitField0_ & ~0x00000004);
        psw_ = getDefaultInstance().getPsw();
        onChanged();
        return this;
      }
      void setPsw(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        psw_ = value;
        onChanged();
      }
      
      // required string imageUrl = 4;
      private java.lang.Object imageUrl_ = "";
      public boolean hasImageUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImageUrl() {
        java.lang.Object ref = imageUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImageUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        imageUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      void setImageUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        imageUrl_ = value;
        onChanged();
      }
      
      // required int32 sex = 5;
      private int sex_ ;
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getSex() {
        return sex_;
      }
      public Builder setSex(int value) {
        bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.LoginC2S)
    }
    
    static {
      defaultInstance = new LoginC2S(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.LoginC2S)
  }
  
  public interface LoginS2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 userId = 1;
    boolean hasUserId();
    int getUserId();
    
    // required int32 status = 2;
    boolean hasStatus();
    int getStatus();
    
    // required string serverIp = 3;
    boolean hasServerIp();
    String getServerIp();
    
    // required int32 port = 4;
    boolean hasPort();
    int getPort();
    
    // required int64 time = 5;
    boolean hasTime();
    long getTime();
  }
  public static final class LoginS2C extends
      com.google.protobuf.GeneratedMessage
      implements LoginS2COrBuilder {
    // Use LoginS2C.newBuilder() to construct.
    private LoginS2C(Builder builder) {
      super(builder);
    }
    private LoginS2C(boolean noInit) {}
    
    private static final LoginS2C defaultInstance;
    public static LoginS2C getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginS2C getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Login.internal_static_Platform_Model_LoginS2C_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Login.internal_static_Platform_Model_LoginS2C_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getStatus() {
      return status_;
    }
    
    // required string serverIp = 3;
    public static final int SERVERIP_FIELD_NUMBER = 3;
    private java.lang.Object serverIp_;
    public boolean hasServerIp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getServerIp() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serverIp_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServerIpBytes() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 port = 4;
    public static final int PORT_FIELD_NUMBER = 4;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPort() {
      return port_;
    }
    
    // required int64 time = 5;
    public static final int TIME_FIELD_NUMBER = 5;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getTime() {
      return time_;
    }
    
    private void initFields() {
      userId_ = 0;
      status_ = 0;
      serverIp_ = "";
      port_ = 0;
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, time_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, port_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Login.LoginS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Login.LoginS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Login.LoginS2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Login.LoginS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Login.internal_static_Platform_Model_LoginS2C_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Login.internal_static_Platform_Model_LoginS2C_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Login.LoginS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serverIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Login.LoginS2C.getDescriptor();
      }
      
      public avatar.protobuf.Login.LoginS2C getDefaultInstanceForType() {
        return avatar.protobuf.Login.LoginS2C.getDefaultInstance();
      }
      
      public avatar.protobuf.Login.LoginS2C build() {
        avatar.protobuf.Login.LoginS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Login.LoginS2C buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Login.LoginS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Login.LoginS2C buildPartial() {
        avatar.protobuf.Login.LoginS2C result = new avatar.protobuf.Login.LoginS2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverIp_ = serverIp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Login.LoginS2C) {
          return mergeFrom((avatar.protobuf.Login.LoginS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Login.LoginS2C other) {
        if (other == avatar.protobuf.Login.LoginS2C.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasServerIp()) {
          setServerIp(other.getServerIp());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasServerIp()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              serverIp_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              port_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              time_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 userId = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 status = 2;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      
      // required string serverIp = 3;
      private java.lang.Object serverIp_ = "";
      public boolean hasServerIp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getServerIp() {
        java.lang.Object ref = serverIp_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serverIp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServerIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        serverIp_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerIp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverIp_ = getDefaultInstance().getServerIp();
        onChanged();
        return this;
      }
      void setServerIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        serverIp_ = value;
        onChanged();
      }
      
      // required int32 port = 4;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000008;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // required int64 time = 5;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000010;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.LoginS2C)
    }
    
    static {
      defaultInstance = new LoginS2C(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.LoginS2C)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_LoginC2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_LoginC2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_LoginS2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_LoginS2C_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ProtoFile/LoginMsg.proto\022\016Platform.Mod" +
      "el\"Q\n\010LoginC2S\022\013\n\003mac\030\001 \002(\t\022\014\n\004name\030\002 \002(" +
      "\t\022\013\n\003psw\030\003 \002(\t\022\020\n\010imageUrl\030\004 \002(\t\022\013\n\003sex\030" +
      "\005 \002(\005\"X\n\010LoginS2C\022\016\n\006userId\030\001 \002(\005\022\016\n\006sta" +
      "tus\030\002 \002(\005\022\020\n\010serverIp\030\003 \002(\t\022\014\n\004port\030\004 \002(" +
      "\005\022\014\n\004time\030\005 \002(\003B\030\n\017avatar.protobufB\005Logi" +
      "n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_Model_LoginC2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_Model_LoginC2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_LoginC2S_descriptor,
              new java.lang.String[] { "Mac", "Name", "Psw", "ImageUrl", "Sex", },
              avatar.protobuf.Login.LoginC2S.class,
              avatar.protobuf.Login.LoginC2S.Builder.class);
          internal_static_Platform_Model_LoginS2C_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_Model_LoginS2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_LoginS2C_descriptor,
              new java.lang.String[] { "UserId", "Status", "ServerIp", "Port", "Time", },
              avatar.protobuf.Login.LoginS2C.class,
              avatar.protobuf.Login.LoginS2C.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
