// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/HallMsg.proto

package avatar.protobuf;

public final class Hall {
  private Hall() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HallConnectVerifyC2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 keyCode = 1;
    boolean hasKeyCode();
    int getKeyCode();
  }
  public static final class HallConnectVerifyC2S extends
      com.google.protobuf.GeneratedMessage
      implements HallConnectVerifyC2SOrBuilder {
    // Use HallConnectVerifyC2S.newBuilder() to construct.
    private HallConnectVerifyC2S(Builder builder) {
      super(builder);
    }
    private HallConnectVerifyC2S(boolean noInit) {}
    
    private static final HallConnectVerifyC2S defaultInstance;
    public static HallConnectVerifyC2S getDefaultInstance() {
      return defaultInstance;
    }
    
    public HallConnectVerifyC2S getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyC2S_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyC2S_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 keyCode = 1;
    public static final int KEYCODE_FIELD_NUMBER = 1;
    private int keyCode_;
    public boolean hasKeyCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getKeyCode() {
      return keyCode_;
    }
    
    private void initFields() {
      keyCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKeyCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keyCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keyCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyC2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Hall.HallConnectVerifyC2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Hall.HallConnectVerifyC2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyC2S_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyC2S_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Hall.HallConnectVerifyC2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        keyCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Hall.HallConnectVerifyC2S.getDescriptor();
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyC2S getDefaultInstanceForType() {
        return avatar.protobuf.Hall.HallConnectVerifyC2S.getDefaultInstance();
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyC2S build() {
        avatar.protobuf.Hall.HallConnectVerifyC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Hall.HallConnectVerifyC2S buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Hall.HallConnectVerifyC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyC2S buildPartial() {
        avatar.protobuf.Hall.HallConnectVerifyC2S result = new avatar.protobuf.Hall.HallConnectVerifyC2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyCode_ = keyCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Hall.HallConnectVerifyC2S) {
          return mergeFrom((avatar.protobuf.Hall.HallConnectVerifyC2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Hall.HallConnectVerifyC2S other) {
        if (other == avatar.protobuf.Hall.HallConnectVerifyC2S.getDefaultInstance()) return this;
        if (other.hasKeyCode()) {
          setKeyCode(other.getKeyCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKeyCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keyCode_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 keyCode = 1;
      private int keyCode_ ;
      public boolean hasKeyCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getKeyCode() {
        return keyCode_;
      }
      public Builder setKeyCode(int value) {
        bitField0_ |= 0x00000001;
        keyCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.HallConnectVerifyC2S)
    }
    
    static {
      defaultInstance = new HallConnectVerifyC2S(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.HallConnectVerifyC2S)
  }
  
  public interface HallConnectVerifyS2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 keyCode = 1;
    boolean hasKeyCode();
    int getKeyCode();
  }
  public static final class HallConnectVerifyS2C extends
      com.google.protobuf.GeneratedMessage
      implements HallConnectVerifyS2COrBuilder {
    // Use HallConnectVerifyS2C.newBuilder() to construct.
    private HallConnectVerifyS2C(Builder builder) {
      super(builder);
    }
    private HallConnectVerifyS2C(boolean noInit) {}
    
    private static final HallConnectVerifyS2C defaultInstance;
    public static HallConnectVerifyS2C getDefaultInstance() {
      return defaultInstance;
    }
    
    public HallConnectVerifyS2C getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyS2C_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyS2C_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 keyCode = 1;
    public static final int KEYCODE_FIELD_NUMBER = 1;
    private int keyCode_;
    public boolean hasKeyCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getKeyCode() {
      return keyCode_;
    }
    
    private void initFields() {
      keyCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKeyCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keyCode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keyCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Hall.HallConnectVerifyS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Hall.HallConnectVerifyS2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Hall.HallConnectVerifyS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyS2C_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Hall.internal_static_Platform_Model_HallConnectVerifyS2C_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Hall.HallConnectVerifyS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        keyCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Hall.HallConnectVerifyS2C.getDescriptor();
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyS2C getDefaultInstanceForType() {
        return avatar.protobuf.Hall.HallConnectVerifyS2C.getDefaultInstance();
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyS2C build() {
        avatar.protobuf.Hall.HallConnectVerifyS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Hall.HallConnectVerifyS2C buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Hall.HallConnectVerifyS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Hall.HallConnectVerifyS2C buildPartial() {
        avatar.protobuf.Hall.HallConnectVerifyS2C result = new avatar.protobuf.Hall.HallConnectVerifyS2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyCode_ = keyCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Hall.HallConnectVerifyS2C) {
          return mergeFrom((avatar.protobuf.Hall.HallConnectVerifyS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Hall.HallConnectVerifyS2C other) {
        if (other == avatar.protobuf.Hall.HallConnectVerifyS2C.getDefaultInstance()) return this;
        if (other.hasKeyCode()) {
          setKeyCode(other.getKeyCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKeyCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keyCode_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 keyCode = 1;
      private int keyCode_ ;
      public boolean hasKeyCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getKeyCode() {
        return keyCode_;
      }
      public Builder setKeyCode(int value) {
        bitField0_ |= 0x00000001;
        keyCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyCode_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.HallConnectVerifyS2C)
    }
    
    static {
      defaultInstance = new HallConnectVerifyS2C(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.HallConnectVerifyS2C)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_HallConnectVerifyC2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_HallConnectVerifyC2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_HallConnectVerifyS2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_HallConnectVerifyS2C_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ProtoFile/HallMsg.proto\022\016Platform.Mode" +
      "l\"\'\n\024HallConnectVerifyC2S\022\017\n\007keyCode\030\001 \002" +
      "(\005\"\'\n\024HallConnectVerifyS2C\022\017\n\007keyCode\030\001 " +
      "\002(\005B\027\n\017avatar.protobufB\004Hall"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_Model_HallConnectVerifyC2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_Model_HallConnectVerifyC2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_HallConnectVerifyC2S_descriptor,
              new java.lang.String[] { "KeyCode", },
              avatar.protobuf.Hall.HallConnectVerifyC2S.class,
              avatar.protobuf.Hall.HallConnectVerifyC2S.Builder.class);
          internal_static_Platform_Model_HallConnectVerifyS2C_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_Model_HallConnectVerifyS2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_HallConnectVerifyS2C_descriptor,
              new java.lang.String[] { "KeyCode", },
              avatar.protobuf.Hall.HallConnectVerifyS2C.class,
              avatar.protobuf.Hall.HallConnectVerifyS2C.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
