// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestPro.proto

package avatar.protobuf;

public final class Test1Proto {
  private Test1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestC2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 userId = 1;
    boolean hasUserId();
    int getUserId();
    
    // repeated .Platform.Model.Array arr = 2;
    java.util.List<avatar.protobuf.Test1Proto.Array> 
        getArrList();
    avatar.protobuf.Test1Proto.Array getArr(int index);
    int getArrCount();
    java.util.List<? extends avatar.protobuf.Test1Proto.ArrayOrBuilder> 
        getArrOrBuilderList();
    avatar.protobuf.Test1Proto.ArrayOrBuilder getArrOrBuilder(
        int index);
  }
  public static final class TestC2S extends
      com.google.protobuf.GeneratedMessage
      implements TestC2SOrBuilder {
    // Use TestC2S.newBuilder() to construct.
    private TestC2S(Builder builder) {
      super(builder);
    }
    private TestC2S(boolean noInit) {}
    
    private static final TestC2S defaultInstance;
    public static TestC2S getDefaultInstance() {
      return defaultInstance;
    }
    
    public TestC2S getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Test1Proto.internal_static_Platform_Model_TestC2S_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Test1Proto.internal_static_Platform_Model_TestC2S_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // repeated .Platform.Model.Array arr = 2;
    public static final int ARR_FIELD_NUMBER = 2;
    private java.util.List<avatar.protobuf.Test1Proto.Array> arr_;
    public java.util.List<avatar.protobuf.Test1Proto.Array> getArrList() {
      return arr_;
    }
    public java.util.List<? extends avatar.protobuf.Test1Proto.ArrayOrBuilder> 
        getArrOrBuilderList() {
      return arr_;
    }
    public int getArrCount() {
      return arr_.size();
    }
    public avatar.protobuf.Test1Proto.Array getArr(int index) {
      return arr_.get(index);
    }
    public avatar.protobuf.Test1Proto.ArrayOrBuilder getArrOrBuilder(
        int index) {
      return arr_.get(index);
    }
    
    private void initFields() {
      userId_ = 0;
      arr_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getArrCount(); i++) {
        if (!getArr(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      for (int i = 0; i < arr_.size(); i++) {
        output.writeMessage(2, arr_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      for (int i = 0; i < arr_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, arr_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.TestC2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Test1Proto.TestC2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Test1Proto.TestC2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Test1Proto.internal_static_Platform_Model_TestC2S_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Test1Proto.internal_static_Platform_Model_TestC2S_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Test1Proto.TestC2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArrFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          arrBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Test1Proto.TestC2S.getDescriptor();
      }
      
      public avatar.protobuf.Test1Proto.TestC2S getDefaultInstanceForType() {
        return avatar.protobuf.Test1Proto.TestC2S.getDefaultInstance();
      }
      
      public avatar.protobuf.Test1Proto.TestC2S build() {
        avatar.protobuf.Test1Proto.TestC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Test1Proto.TestC2S buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Test1Proto.TestC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Test1Proto.TestC2S buildPartial() {
        avatar.protobuf.Test1Proto.TestC2S result = new avatar.protobuf.Test1Proto.TestC2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (arrBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            arr_ = java.util.Collections.unmodifiableList(arr_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.arr_ = arr_;
        } else {
          result.arr_ = arrBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Test1Proto.TestC2S) {
          return mergeFrom((avatar.protobuf.Test1Proto.TestC2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Test1Proto.TestC2S other) {
        if (other == avatar.protobuf.Test1Proto.TestC2S.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (arrBuilder_ == null) {
          if (!other.arr_.isEmpty()) {
            if (arr_.isEmpty()) {
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArrIsMutable();
              arr_.addAll(other.arr_);
            }
            onChanged();
          }
        } else {
          if (!other.arr_.isEmpty()) {
            if (arrBuilder_.isEmpty()) {
              arrBuilder_.dispose();
              arrBuilder_ = null;
              arr_ = other.arr_;
              bitField0_ = (bitField0_ & ~0x00000002);
              arrBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArrFieldBuilder() : null;
            } else {
              arrBuilder_.addAllMessages(other.arr_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        for (int i = 0; i < getArrCount(); i++) {
          if (!getArr(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              avatar.protobuf.Test1Proto.Array.Builder subBuilder = avatar.protobuf.Test1Proto.Array.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addArr(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 userId = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .Platform.Model.Array arr = 2;
      private java.util.List<avatar.protobuf.Test1Proto.Array> arr_ =
        java.util.Collections.emptyList();
      private void ensureArrIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          arr_ = new java.util.ArrayList<avatar.protobuf.Test1Proto.Array>(arr_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          avatar.protobuf.Test1Proto.Array, avatar.protobuf.Test1Proto.Array.Builder, avatar.protobuf.Test1Proto.ArrayOrBuilder> arrBuilder_;
      
      public java.util.List<avatar.protobuf.Test1Proto.Array> getArrList() {
        if (arrBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arr_);
        } else {
          return arrBuilder_.getMessageList();
        }
      }
      public int getArrCount() {
        if (arrBuilder_ == null) {
          return arr_.size();
        } else {
          return arrBuilder_.getCount();
        }
      }
      public avatar.protobuf.Test1Proto.Array getArr(int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);
        } else {
          return arrBuilder_.getMessage(index);
        }
      }
      public Builder setArr(
          int index, avatar.protobuf.Test1Proto.Array value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.set(index, value);
          onChanged();
        } else {
          arrBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setArr(
          int index, avatar.protobuf.Test1Proto.Array.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addArr(avatar.protobuf.Test1Proto.Array value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(value);
          onChanged();
        } else {
          arrBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addArr(
          int index, avatar.protobuf.Test1Proto.Array value) {
        if (arrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrIsMutable();
          arr_.add(index, value);
          onChanged();
        } else {
          arrBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addArr(
          avatar.protobuf.Test1Proto.Array.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addArr(
          int index, avatar.protobuf.Test1Proto.Array.Builder builderForValue) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllArr(
          java.lang.Iterable<? extends avatar.protobuf.Test1Proto.Array> values) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          super.addAll(values, arr_);
          onChanged();
        } else {
          arrBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearArr() {
        if (arrBuilder_ == null) {
          arr_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          arrBuilder_.clear();
        }
        return this;
      }
      public Builder removeArr(int index) {
        if (arrBuilder_ == null) {
          ensureArrIsMutable();
          arr_.remove(index);
          onChanged();
        } else {
          arrBuilder_.remove(index);
        }
        return this;
      }
      public avatar.protobuf.Test1Proto.Array.Builder getArrBuilder(
          int index) {
        return getArrFieldBuilder().getBuilder(index);
      }
      public avatar.protobuf.Test1Proto.ArrayOrBuilder getArrOrBuilder(
          int index) {
        if (arrBuilder_ == null) {
          return arr_.get(index);  } else {
          return arrBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends avatar.protobuf.Test1Proto.ArrayOrBuilder> 
           getArrOrBuilderList() {
        if (arrBuilder_ != null) {
          return arrBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arr_);
        }
      }
      public avatar.protobuf.Test1Proto.Array.Builder addArrBuilder() {
        return getArrFieldBuilder().addBuilder(
            avatar.protobuf.Test1Proto.Array.getDefaultInstance());
      }
      public avatar.protobuf.Test1Proto.Array.Builder addArrBuilder(
          int index) {
        return getArrFieldBuilder().addBuilder(
            index, avatar.protobuf.Test1Proto.Array.getDefaultInstance());
      }
      public java.util.List<avatar.protobuf.Test1Proto.Array.Builder> 
           getArrBuilderList() {
        return getArrFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          avatar.protobuf.Test1Proto.Array, avatar.protobuf.Test1Proto.Array.Builder, avatar.protobuf.Test1Proto.ArrayOrBuilder> 
          getArrFieldBuilder() {
        if (arrBuilder_ == null) {
          arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              avatar.protobuf.Test1Proto.Array, avatar.protobuf.Test1Proto.Array.Builder, avatar.protobuf.Test1Proto.ArrayOrBuilder>(
                  arr_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          arr_ = null;
        }
        return arrBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.TestC2S)
    }
    
    static {
      defaultInstance = new TestC2S(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.TestC2S)
  }
  
  public interface ArrayOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
  }
  public static final class Array extends
      com.google.protobuf.GeneratedMessage
      implements ArrayOrBuilder {
    // Use Array.newBuilder() to construct.
    private Array(Builder builder) {
      super(builder);
    }
    private Array(boolean noInit) {}
    
    private static final Array defaultInstance;
    public static Array getDefaultInstance() {
      return defaultInstance;
    }
    
    public Array getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avatar.protobuf.Test1Proto.internal_static_Platform_Model_Array_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avatar.protobuf.Test1Proto.internal_static_Platform_Model_Array_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    private void initFields() {
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Test1Proto.Array parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static avatar.protobuf.Test1Proto.Array parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(avatar.protobuf.Test1Proto.Array prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements avatar.protobuf.Test1Proto.ArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avatar.protobuf.Test1Proto.internal_static_Platform_Model_Array_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avatar.protobuf.Test1Proto.internal_static_Platform_Model_Array_fieldAccessorTable;
      }
      
      // Construct using avatar.protobuf.Test1Proto.Array.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avatar.protobuf.Test1Proto.Array.getDescriptor();
      }
      
      public avatar.protobuf.Test1Proto.Array getDefaultInstanceForType() {
        return avatar.protobuf.Test1Proto.Array.getDefaultInstance();
      }
      
      public avatar.protobuf.Test1Proto.Array build() {
        avatar.protobuf.Test1Proto.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private avatar.protobuf.Test1Proto.Array buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        avatar.protobuf.Test1Proto.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public avatar.protobuf.Test1Proto.Array buildPartial() {
        avatar.protobuf.Test1Proto.Array result = new avatar.protobuf.Test1Proto.Array(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avatar.protobuf.Test1Proto.Array) {
          return mergeFrom((avatar.protobuf.Test1Proto.Array)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(avatar.protobuf.Test1Proto.Array other) {
        if (other == avatar.protobuf.Test1Proto.Array.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Platform.Model.Array)
    }
    
    static {
      defaultInstance = new Array(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Platform.Model.Array)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_TestC2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_TestC2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_Array_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_Array_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTestPro.proto\022\016Platform.Model\"=\n\007TestC" +
      "2S\022\016\n\006userId\030\001 \002(\005\022\"\n\003arr\030\002 \003(\0132\025.Platfo" +
      "rm.Model.Array\"\023\n\005Array\022\n\n\002id\030\001 \002(\005B\035\n\017a" +
      "vatar.protobufB\nTest1Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_Model_TestC2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_Model_TestC2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_TestC2S_descriptor,
              new java.lang.String[] { "UserId", "Arr", },
              avatar.protobuf.Test1Proto.TestC2S.class,
              avatar.protobuf.Test1Proto.TestC2S.Builder.class);
          internal_static_Platform_Model_Array_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_Model_Array_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_Array_descriptor,
              new java.lang.String[] { "Id", },
              avatar.protobuf.Test1Proto.Array.class,
              avatar.protobuf.Test1Proto.Array.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
