//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoFile/BattleBackMsg.proto
// Note: requires additional types generated from: ProtoFile/BattleMsg.proto
namespace Platform.Model
{
}